import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const analectsOnXueqi = {
  meta: {
    sourceText: "少之時，血氣未定及其壯也，血氣方剛及其老也，血氣既衰",
    targetText:
      "In youth, blood and vital energy are not yet settled; in maturity, blood and vital energy are at full strength; in old age, blood and vital energy have already declined.",
    provenance: "The Analects 16.7",
  },
  sourceTokens: [
    { id: 0, text: "少", pinyin: "shao3", line: 0, type: "character" },
    { id: 1, text: "之", pinyin: undefined, line: 0, type: "character" },
    { id: 2, text: "時", pinyin: undefined, line: 0, type: "character" },
    { id: 3, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 4, text: "血", pinyin: "xue4", line: 0, type: "character" },
    { id: 5, text: "氣", pinyin: "qi4", line: 0, type: "character" },
    { id: 6, text: "未", pinyin: "wei4", line: 0, type: "character" },
    { id: 7, text: "定", pinyin: "ding4", line: 0, type: "character" },
    { id: 8, text: "及", pinyin: undefined, line: 1, type: "character" },
    { id: 9, text: "其", pinyin: undefined, line: 1, type: "character" },
    { id: 10, text: "壯", pinyin: "zhuang4", line: 1, type: "character" },
    { id: 11, text: "也", pinyin: undefined, line: 1, type: "character" },
    { id: 12, text: "，", pinyin: null, line: 1, type: "punctuation" },
    { id: 13, text: "血", pinyin: "xue4", line: 1, type: "character" },
    { id: 14, text: "氣", pinyin: "qi4", line: 1, type: "character" },
    { id: 15, text: "方", pinyin: "fang1", line: 1, type: "character" },
    { id: 16, text: "剛", pinyin: "gang1", line: 1, type: "character" },
    { id: 17, text: "及", pinyin: undefined, line: 2, type: "character" },
    { id: 18, text: "其", pinyin: undefined, line: 2, type: "character" },
    { id: 19, text: "老", pinyin: "lao3", line: 2, type: "character" },
    { id: 20, text: "也", pinyin: undefined, line: 2, type: "character" },
    { id: 21, text: "，", pinyin: null, line: 2, type: "punctuation" },
    { id: 22, text: "血", pinyin: "xue4", line: 2, type: "character" },
    { id: 23, text: "氣", pinyin: "qi4", line: 2, type: "character" },
    { id: 24, text: "既", pinyin: "ji4", line: 2, type: "character" },
    { id: 25, text: "衰", pinyin: "shuai1", line: 2, type: "character" },
  ],
  targetTokens: [
    { id: 0, text: "In", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "youth,", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "blood", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "and", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "vital", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "energy", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "are", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "not", line: 0, type: "text" },
    { id: 15, text: " ", line: 0, type: "whitespace" },
    { id: 16, text: "yet", line: 0, type: "text" },
    { id: 17, text: " ", line: 0, type: "whitespace" },
    { id: 18, text: "settled;", line: 0, type: "text" },
    { id: 19, text: " ", line: 0, type: "whitespace" },
    { id: 20, text: "in", line: 1, type: "text" },
    { id: 21, text: " ", line: 1, type: "whitespace" },
    { id: 22, text: "maturity,", line: 1, type: "text" },
    { id: 23, text: " ", line: 1, type: "whitespace" },
    { id: 24, text: "blood", line: 1, type: "text" },
    { id: 25, text: " ", line: 1, type: "whitespace" },
    { id: 26, text: "and", line: 1, type: "text" },
    { id: 27, text: " ", line: 1, type: "whitespace" },
    { id: 28, text: "vital", line: 1, type: "text" },
    { id: 29, text: " ", line: 1, type: "whitespace" },
    { id: 30, text: "energy", line: 1, type: "text" },
    { id: 31, text: " ", line: 1, type: "whitespace" },
    { id: 32, text: "are", line: 1, type: "text" },
    { id: 33, text: " ", line: 1, type: "whitespace" },
    { id: 34, text: "at", line: 1, type: "text" },
    { id: 35, text: " ", line: 1, type: "whitespace" },
    { id: 36, text: "full", line: 1, type: "text" },
    { id: 37, text: " ", line: 1, type: "whitespace" },
    { id: 38, text: "strength;", line: 1, type: "text" },
    { id: 39, text: " ", line: 1, type: "whitespace" },
    { id: 40, text: "in", line: 2, type: "text" },
    { id: 41, text: " ", line: 2, type: "whitespace" },
    { id: 42, text: "old", line: 2, type: "text" },
    { id: 43, text: " ", line: 2, type: "whitespace" },
    { id: 44, text: "age,", line: 2, type: "text" },
    { id: 45, text: " ", line: 2, type: "whitespace" },
    { id: 46, text: "blood", line: 2, type: "text" },
    { id: 47, text: " ", line: 2, type: "whitespace" },
    { id: 48, text: "and", line: 2, type: "text" },
    { id: 49, text: " ", line: 2, type: "whitespace" },
    { id: 50, text: "vital", line: 2, type: "text" },
    { id: 51, text: " ", line: 2, type: "whitespace" },
    { id: 52, text: "energy", line: 2, type: "text" },
    { id: 53, text: " ", line: 2, type: "whitespace" },
    { id: 54, text: "have", line: 2, type: "text" },
    { id: 55, text: " ", line: 2, type: "whitespace" },
    { id: 56, text: "already", line: 2, type: "text" },
    { id: 57, text: " ", line: 2, type: "whitespace" },
    { id: 58, text: "declined.", line: 2, type: "text" },
  ],
  mappings: [
    {
      id: "818ba0f6-32a6-4910-9066-4ec7a4bfa34b",
      sourceTokenIds: [0],
      targetTokenIds: [2],
    },
    {
      id: "ad58f8a0-387d-419f-a603-8fab73ad2c63",
      sourceTokenIds: [4],
      targetTokenIds: [4],
    },
    {
      id: "643d8fec-5873-4a82-bdd9-5dda4a0a05c1",
      sourceTokenIds: [5],
      targetTokenIds: [8, 10],
    },
    {
      id: "2561340b-61dc-4e6b-849c-c67c7bc4ccdd",
      sourceTokenIds: [6],
      targetTokenIds: [14, 16],
    },
    {
      id: "65494b4a-b98a-4f55-807b-a29a7cf1ff28",
      sourceTokenIds: [7],
      targetTokenIds: [18],
    },
    {
      id: "b70d6464-c642-4db6-8240-719d8f86c5f1",
      sourceTokenIds: [10],
      targetTokenIds: [22],
    },
    {
      id: "652adc8a-7f32-48e3-918c-836bb4387d0b",
      sourceTokenIds: [13],
      targetTokenIds: [24],
    },
    {
      id: "527b343c-2c45-4e41-9d87-27ca3d04e678",
      sourceTokenIds: [14],
      targetTokenIds: [28, 30],
    },
    {
      id: "28df17b4-8086-40fd-8b34-e738b6939a14",
      sourceTokenIds: [15],
      targetTokenIds: [34],
    },
    {
      id: "993098e2-8e98-4fc6-b9d5-08a840d5cffc",
      sourceTokenIds: [16],
      targetTokenIds: [36, 38],
    },
    {
      id: "862bb97e-bf5a-4ab6-9f10-83be242180db",
      sourceTokenIds: [19],
      targetTokenIds: [44, 42],
    },
    {
      id: "cc8fc609-6ac2-4055-bc78-be90342cb1ca",
      sourceTokenIds: [22],
      targetTokenIds: [46],
    },
    {
      id: "f847919f-8bc3-4013-8851-a6a370fb6fc8",
      sourceTokenIds: [23],
      targetTokenIds: [50, 52],
    },
    {
      id: "ff40403f-f899-4fdb-bd55-5765c55b14ca",
      sourceTokenIds: [24],
      targetTokenIds: [56],
    },
    {
      id: "1a62ecc6-770b-4b04-a453-7e66e3a2edd4",
      sourceTokenIds: [25],
      targetTokenIds: [58],
    },
  ],
} satisfies QuoteSlicerExport;
