import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const l001cQ03GovernsBelow = {
  meta: {
    sourceText: "居高理下，為人經緯，故其字一大以鎮之也。",
    targetText:
      "It sits above and governs what is below, as warp and weft to man. Therefore, its written form: the sky [above] man, thus holding him in his place.",
    provenance: "Jingdian Shiwen",
  },
  sourceTokens: [
    { id: 0, text: "居", pinyin: "ju1", line: 0, type: "character" },
    { id: 1, text: "高", pinyin: "gao1", line: 0, type: "character" },
    { id: 2, text: "理", pinyin: "li3", line: 0, type: "character" },
    { id: 3, text: "下", pinyin: "xia4", line: 0, type: "character" },
    { id: 4, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 5, text: "為", pinyin: "wei2", line: 0, type: "character" },
    { id: 6, text: "人", pinyin: "ren2", line: 0, type: "character" },
    { id: 7, text: "經", pinyin: "jing1", line: 0, type: "character" },
    { id: 8, text: "緯", pinyin: "wei3", line: 0, type: "character" },
    { id: 9, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 10, text: "故", pinyin: "gu4", line: 1, type: "character" },
    { id: 11, text: "其", pinyin: "qi2", line: 1, type: "character" },
    { id: 12, text: "字", pinyin: "zi4", line: 1, type: "character" },
    { id: 13, text: "一", pinyin: "yi1", line: 1, type: "character" },
    { id: 14, text: "大", pinyin: "da4", line: 1, type: "character" },
    { id: 15, text: "以", pinyin: "yi3", line: 1, type: "character" },
    { id: 16, text: "鎮", pinyin: "zhen4", line: 1, type: "character" },
    { id: 17, text: "之", pinyin: "zhi1", line: 1, type: "character" },
    { id: 18, text: "也", pinyin: undefined, line: 1, type: "character" },
    { id: 19, text: "。", pinyin: null, line: 1, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "It", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "sits", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "above", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "and", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "governs", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "what", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "is", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "below,", line: 0, type: "text" },
    { id: 15, text: " ", line: 0, type: "whitespace" },
    { id: 16, text: "as", line: 0, type: "text" },
    { id: 17, text: " ", line: 0, type: "whitespace" },
    { id: 18, text: "warp", line: 0, type: "text" },
    { id: 19, text: " ", line: 0, type: "whitespace" },
    { id: 20, text: "and", line: 0, type: "text" },
    { id: 21, text: " ", line: 0, type: "whitespace" },
    { id: 22, text: "weft", line: 0, type: "text" },
    { id: 23, text: " ", line: 0, type: "whitespace" },
    { id: 24, text: "to", line: 0, type: "text" },
    { id: 25, text: " ", line: 0, type: "whitespace" },
    { id: 26, text: "man.", line: 0, type: "text" },
    { id: 27, text: " ", line: 0, type: "whitespace" },
    { id: 28, text: "Therefore,", line: 1, type: "text" },
    { id: 29, text: " ", line: 1, type: "whitespace" },
    { id: 30, text: "its", line: 1, type: "text" },
    { id: 31, text: " ", line: 1, type: "whitespace" },
    { id: 32, text: "written", line: 1, type: "text" },
    { id: 33, text: " ", line: 1, type: "whitespace" },
    { id: 34, text: "form:", line: 1, type: "text" },
    { id: 35, text: " ", line: 1, type: "whitespace" },
    { id: 36, text: "the", line: 1, type: "text" },
    { id: 37, text: " ", line: 1, type: "whitespace" },
    { id: 38, text: "sky", line: 1, type: "text" },
    { id: 39, text: " ", line: 1, type: "whitespace" },
    { id: 40, text: "[above]", line: 1, type: "text" },
    { id: 41, text: " ", line: 1, type: "whitespace" },
    { id: 42, text: "man,", line: 1, type: "text" },
    { id: 43, text: " ", line: 1, type: "whitespace" },
    { id: 44, text: "thus", line: 1, type: "text" },
    { id: 45, text: " ", line: 1, type: "whitespace" },
    { id: 46, text: "holding", line: 1, type: "text" },
    { id: 47, text: " ", line: 1, type: "whitespace" },
    { id: 48, text: "him", line: 1, type: "text" },
    { id: 49, text: " ", line: 1, type: "whitespace" },
    { id: 50, text: "in", line: 1, type: "text" },
    { id: 51, text: " ", line: 1, type: "whitespace" },
    { id: 52, text: "his", line: 1, type: "text" },
    { id: 53, text: " ", line: 1, type: "whitespace" },
    { id: 54, text: "place.", line: 1, type: "text" },
    { id: 55, text: " ", line: 1, type: "whitespace" },
  ],
  mappings: [
    {
      id: "68529205-358d-4a54-b67f-35e3cdacb57a",
      sourceTokenIds: [13],
      targetTokenIds: [38, 36],
    },
    {
      id: "abc88664-356c-454a-a3b9-d7b03422361c",
      sourceTokenIds: [14],
      targetTokenIds: [42],
    },
    {
      id: "55bee6d5-a78a-448d-95ba-d72630f64c7b",
      sourceTokenIds: [15],
      targetTokenIds: [44],
    },
    {
      id: "013cdf66-f05c-496a-b553-a0b57c7a2d09",
      sourceTokenIds: [16],
      targetTokenIds: [46, 50, 54],
    },
    {
      id: "dfd7cc90-0971-46ef-853d-c3221e414516",
      sourceTokenIds: [17],
      targetTokenIds: [48],
    },
    {
      id: "985d30fb-23ac-4383-811a-83acb4a0bd76",
      sourceTokenIds: [12],
      targetTokenIds: [32, 34],
    },
    {
      id: "4dc7a566-1ea7-4bd6-aa4f-cf91dfb6c09f",
      sourceTokenIds: [11],
      targetTokenIds: [30],
    },
    {
      id: "d4a94e9b-1f37-4060-8f6d-225ecc1a2b7e",
      sourceTokenIds: [10],
      targetTokenIds: [28],
    },
    {
      id: "3f958b48-0aba-4ac7-a036-2dcf2b47b176",
      sourceTokenIds: [3],
      targetTokenIds: [14, 12, 10],
    },
    {
      id: "4c317d32-0372-4e6d-a319-c581813f3b05",
      sourceTokenIds: [6],
      targetTokenIds: [26],
    },
    {
      id: "f67ca710-7886-4092-88d7-28434b975a92",
      sourceTokenIds: [5],
      targetTokenIds: [16],
    },
    {
      id: "dc92240e-a6cc-4ce3-9233-be0e47320f26",
      sourceTokenIds: [0],
      targetTokenIds: [2, 0],
    },
    {
      id: "c1794fbd-ae4e-491d-bc79-587945957ae0",
      sourceTokenIds: [1],
      targetTokenIds: [4],
    },
    {
      id: "86e3cc92-2e02-4a6d-aaf6-a0dd0fd18723",
      sourceTokenIds: [2],
      targetTokenIds: [8],
    },
    {
      id: "5ede3a76-621e-41b8-92b5-8e2b37cdffb0",
      sourceTokenIds: [7],
      targetTokenIds: [18],
    },
    {
      id: "033fbe82-19e2-4d15-bafe-0fca81fcf282",
      sourceTokenIds: [8],
      targetTokenIds: [22],
    },
  ],
} satisfies QuoteSlicerExport;
