import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001bQ01WaterDescends = {
  attestation: {
    tokens: [
      { id: 0, text: "水", pinyin: "shui3", type: "character" },
      { id: 1, text: "从", pinyin: "cong2", type: "character" },
      { id: 2, text: "雲", pinyin: "yun2", type: "character" },
      { id: 3, text: "下", pinyin: "xia4", type: "character" },
      { id: 4, text: "也", pinyin: undefined, type: "character" },
      { id: 5, text: "。", pinyin: null, type: "punctuation" },
      { id: 6, text: "一", pinyin: "yi1", type: "character" },
      { id: 7, text: "象", pinyin: "xiang4", type: "character" },
      { id: 8, text: "天", pinyin: "tian1", type: "character" },
      { id: 9, text: "，", pinyin: null, type: "punctuation" },
      { id: 10, text: "冂", pinyin: "jiong1", type: "character" },
      { id: 11, text: "象", pinyin: "xiang4", type: "character" },
      { id: 12, text: "雲", pinyin: "yun2", type: "character" },
      { id: 13, text: "，", pinyin: null, type: "punctuation" },
      { id: 14, text: "水", pinyin: "shui3", type: "character" },
      { id: 15, text: "霝", pinyin: "ling2", type: "character" },
      { id: 16, text: "其", pinyin: "qi2", type: "character" },
      { id: 17, text: "閒", pinyin: "xian2", type: "character" },
      { id: 18, text: "也", pinyin: undefined, type: "character" },
      { id: 19, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "Water", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "descends", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "from", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "the", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "clouds.", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "一", type: "hanzi" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "represents", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "heaven;", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "冂", type: "hanzi" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "represents", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "a", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "cloud;", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "water", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "falls", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "between", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "them.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "92116250-17ea-407c-9266-f4be70110cd4",
        sourceTokenIds: [0],
        targetTokenIds: [0],
      },
      {
        id: "cf0f5581-7be5-4111-9794-953a5ff3f5ac",
        sourceTokenIds: [2],
        targetTokenIds: [8, 6],
      },
      {
        id: "7851d1f0-149b-4b57-830b-733a49401ed4",
        sourceTokenIds: [3],
        targetTokenIds: [2],
      },
      {
        id: "61e4f420-94e3-449e-b81e-29500ab7f1ad",
        sourceTokenIds: [1],
        targetTokenIds: [4],
      },
      {
        id: "15e99b60-5901-4ed4-9b98-733e3d4ccac7",
        sourceTokenIds: [6],
        targetTokenIds: [10],
      },
      {
        id: "16f93e1f-502f-404f-9a2e-2baa2cfb3d10",
        sourceTokenIds: [7],
        targetTokenIds: [12],
      },
      {
        id: "c49ad849-8e92-4dae-86e6-409837284c29",
        sourceTokenIds: [8],
        targetTokenIds: [14],
      },
      {
        id: "412b11c9-5a7a-493d-a8d3-63ee9d1d3499",
        sourceTokenIds: [10],
        targetTokenIds: [16],
      },
      {
        id: "0c01f6b2-3b86-4e78-b750-322a82af05e7",
        sourceTokenIds: [11],
        targetTokenIds: [18],
      },
      {
        id: "11b6afa2-b9d5-48c0-9307-0ead7f4f364c",
        sourceTokenIds: [12],
        targetTokenIds: [22, 20],
      },
      {
        id: "00209a2e-d061-409b-99af-bccd7bf144de",
        sourceTokenIds: [14],
        targetTokenIds: [24],
      },
      {
        id: "16c1c5ce-32aa-46c5-941f-a91fcf5281b5",
        sourceTokenIds: [15],
        targetTokenIds: [26],
      },
      {
        id: "4f213c39-3b09-46f4-82d8-78b076530706",
        sourceTokenIds: [17],
        targetTokenIds: [28],
      },
      {
        id: "c730a44e-3eff-4f80-8f85-f1ae72cba9b2",
        sourceTokenIds: [16],
        targetTokenIds: [30],
      },
    ],
    breaks: {
      attestation: [6],
      translation: [10, 24],
    },
  },
} satisfies AttestationTranslationAlignment;
