import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001cQ01HeavenHighest = {
  attestation: {
    tokens: [
      { id: 0, text: "天", pinyin: "tian1", type: "character" },
      { id: 1, text: "顚", pinyin: "dian1", type: "character" },
      { id: 2, text: "也", pinyin: "ye3", type: "character" },
      { id: 3, text: "。", pinyin: null, type: "punctuation" },
      { id: 4, text: "至", pinyin: "zhi4", type: "character" },
      { id: 5, text: "高", pinyin: "gao1", type: "character" },
      { id: 6, text: "無", pinyin: "wu2", type: "character" },
      { id: 7, text: "上", pinyin: "shang4", type: "character" },
      { id: 8, text: "，", pinyin: null, type: "punctuation" },
      { id: 9, text: "从", pinyin: "cong2", type: "character" },
      { id: 10, text: "一", pinyin: "yi1", type: "character" },
      { id: 11, text: "大", pinyin: "da4", type: "character" },
      { id: 12, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "天", type: "hanzi" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "is", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "the", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "highest.", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "It", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "is", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "supremely", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "high,", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "there", type: "text" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "is", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "nothing", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "above", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "it.", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "It", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "is", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "composed", type: "text" },
      { id: 31, text: " ", type: "whitespace" },
      { id: 32, text: "of", type: "text" },
      { id: 33, text: " ", type: "whitespace" },
      { id: 34, text: "一", type: "hanzi" },
      { id: 35, text: " ", type: "whitespace" },
      { id: 36, text: "and", type: "text" },
      { id: 37, text: " ", type: "whitespace" },
      { id: 38, text: "大", type: "hanzi" },
      { id: 39, text: ".", type: "punctuation" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "8abcb668-68ce-41a9-adbc-f958e18ac0d4",
        sourceTokenIds: [0],
        targetTokenIds: [0],
      },
      {
        id: "0bcdb7d1-0850-4c1a-a263-c19631cf5b96",
        sourceTokenIds: [1],
        targetTokenIds: [6, 4],
      },
      {
        id: "e87213ad-11c1-4371-a240-4184ad318302",
        sourceTokenIds: [2],
        targetTokenIds: [2],
      },
      {
        id: "1ad2d34a-3f39-4815-8dd8-51344e59cc40",
        sourceTokenIds: [4],
        targetTokenIds: [12],
      },
      {
        id: "dcf28c9c-3e11-4a1b-b67d-893a54639d62",
        sourceTokenIds: [5],
        targetTokenIds: [14],
      },
      {
        id: "543ce091-a69c-4c1c-9688-1f6b07fcd7f1",
        sourceTokenIds: [6],
        targetTokenIds: [20],
      },
      {
        id: "e85f4136-37b9-4907-8e66-3d1aa5131472",
        sourceTokenIds: [7],
        targetTokenIds: [22],
      },
      {
        id: "29a18c3c-b312-4a12-81d4-9d662cf9ddf2",
        sourceTokenIds: [9],
        targetTokenIds: [30, 32],
      },
      {
        id: "80eb6256-c9dc-44bc-aa50-d1ac5248b886",
        sourceTokenIds: [10],
        targetTokenIds: [34],
      },
      {
        id: "476a2431-3242-409d-a3dc-2c01997752bc",
        sourceTokenIds: [11],
        targetTokenIds: [38],
      },
    ],
    breaks: {
      attestation: [],
      translation: [8, 26],
    },
  },
} satisfies AttestationTranslationAlignment;
