import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001cQ02HeavenAboveMan = {
  attestation: {
    tokens: [
      { id: 0, text: "按", pinyin: "an4", type: "character" },
      { id: 1, text: "大", pinyin: "da4", type: "character" },
      { id: 2, text: "猶", pinyin: "you2", type: "character" },
      { id: 3, text: "人", pinyin: "ren2", type: "character" },
      { id: 4, text: "也", pinyin: undefined, type: "character" },
      { id: 5, text: "，", pinyin: null, type: "punctuation" },
      { id: 6, text: "天", pinyin: "tian1", type: "character" },
      { id: 7, text: "在", pinyin: "zai4", type: "character" },
      { id: 8, text: "人", pinyin: "ren2", type: "character" },
      { id: 9, text: "上", pinyin: "shang4", type: "character" },
      { id: 10, text: "，", pinyin: null, type: "punctuation" },
      { id: 11, text: "仰", pinyin: "yang3", type: "character" },
      { id: 12, text: "首", pinyin: "shou3", type: "character" },
      { id: 13, text: "見", pinyin: "jian4", type: "character" },
      { id: 14, text: "之", pinyin: "zhi1", type: "character" },
      { id: 15, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "Note:", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "大", type: "hanzi" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "resembles", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "a", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "person.", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "Heaven", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "is", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "above", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "man;", type: "text" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "raising", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "his", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "head,", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "he", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "sees", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "it.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "9b67bf55-669d-44f0-8bd8-955def9f2ade",
        sourceTokenIds: [0],
        targetTokenIds: [0],
      },
      {
        id: "99f71516-7121-44b1-8993-4dcd02afc0a9",
        sourceTokenIds: [1],
        targetTokenIds: [2],
      },
      {
        id: "9fd9361d-05ce-4a86-96e2-66b23deb7606",
        sourceTokenIds: [2],
        targetTokenIds: [4],
      },
      {
        id: "275b25f0-7eaf-4628-959e-52f70ef03c75",
        sourceTokenIds: [3],
        targetTokenIds: [8, 6],
      },
      {
        id: "237af2d7-39ce-43b0-b0f1-de635dfc9364",
        sourceTokenIds: [6],
        targetTokenIds: [10],
      },
      {
        id: "61583817-1d15-4b36-845b-beba497bd534",
        sourceTokenIds: [7],
        targetTokenIds: [12],
      },
      {
        id: "1f14c193-10ff-402c-a42c-b2c6740f6500",
        sourceTokenIds: [8],
        targetTokenIds: [16],
      },
      {
        id: "9cc5f98d-eae4-4069-999e-6b74061e390b",
        sourceTokenIds: [9],
        targetTokenIds: [14],
      },
      {
        id: "2c209be8-ec01-421f-94ac-016837110b27",
        sourceTokenIds: [11],
        targetTokenIds: [18],
      },
      {
        id: "55b793b3-799d-426f-a4dc-76b821cfa0e4",
        sourceTokenIds: [12],
        targetTokenIds: [22, 20],
      },
      {
        id: "9188aadf-b523-4d17-8d60-e97dca7243bf",
        sourceTokenIds: [13],
        targetTokenIds: [26, 24],
      },
      {
        id: "8b63c202-5552-4a87-802f-735901537fcc",
        sourceTokenIds: [14],
        targetTokenIds: [28],
      },
    ],
    breaks: {
      attestation: [],
      translation: [10],
    },
  },
} satisfies AttestationTranslationAlignment;
