import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const l001jQ01SacrificialBlood = {
  meta: {
    sourceText: "祭所薦牲血也。从皿，一象血形。",
    targetText:
      "At a sacrifice, that which is presented is the blood of the sacrificial victim. Formed from a vessel; the stroke depicts the blood.",
    provenance: "Shuowen Jiezi",
  },
  sourceTokens: [
    { id: 0, text: "祭", pinyin: "ji4", line: 0, type: "character" },
    { id: 1, text: "所", pinyin: "suo3", line: 0, type: "character" },
    { id: 2, text: "薦", pinyin: "jian4", line: 0, type: "character" },
    { id: 3, text: "牲", pinyin: "sheng1", line: 0, type: "character" },
    { id: 4, text: "血", pinyin: "xue4", line: 0, type: "character" },
    { id: 5, text: "也", pinyin: "ye3", line: 0, type: "character" },
    { id: 6, text: "。", pinyin: null, line: 0, type: "punctuation" },
    { id: 7, text: "从", pinyin: "cong2", line: 1, type: "character" },
    { id: 8, text: "皿", pinyin: "min3", line: 1, type: "character" },
    { id: 9, text: "，", pinyin: null, line: 1, type: "punctuation" },
    { id: 10, text: "一", pinyin: "yi1", line: 1, type: "character" },
    { id: 11, text: "象", pinyin: "xiang4", line: 1, type: "character" },
    { id: 12, text: "血", pinyin: "xue4", line: 1, type: "character" },
    { id: 13, text: "形", pinyin: "xing2", line: 1, type: "character" },
    { id: 14, text: "。", pinyin: null, line: 1, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "At", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "a", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "sacrifice,", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "that", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "which", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "is", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "presented", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "is", line: 0, type: "text" },
    { id: 15, text: " ", line: 0, type: "whitespace" },
    { id: 16, text: "the", line: 0, type: "text" },
    { id: 17, text: " ", line: 0, type: "whitespace" },
    { id: 18, text: "blood", line: 0, type: "text" },
    { id: 19, text: " ", line: 0, type: "whitespace" },
    { id: 20, text: "of", line: 0, type: "text" },
    { id: 21, text: " ", line: 0, type: "whitespace" },
    { id: 22, text: "the", line: 0, type: "text" },
    { id: 23, text: " ", line: 0, type: "whitespace" },
    { id: 24, text: "sacrificial", line: 0, type: "text" },
    { id: 25, text: " ", line: 0, type: "whitespace" },
    { id: 26, text: "victim.", line: 0, type: "text" },
    { id: 27, text: " ", line: 0, type: "whitespace" },
    { id: 28, text: "Formed", line: 1, type: "text" },
    { id: 29, text: " ", line: 1, type: "whitespace" },
    { id: 30, text: "from", line: 1, type: "text" },
    { id: 31, text: " ", line: 1, type: "whitespace" },
    { id: 32, text: "a", line: 1, type: "text" },
    { id: 33, text: " ", line: 1, type: "whitespace" },
    { id: 34, text: "vessel;", line: 1, type: "text" },
    { id: 35, text: " ", line: 1, type: "whitespace" },
    { id: 36, text: "the", line: 1, type: "text" },
    { id: 37, text: " ", line: 1, type: "whitespace" },
    { id: 38, text: "stroke", line: 1, type: "text" },
    { id: 39, text: " ", line: 1, type: "whitespace" },
    { id: 40, text: "depicts", line: 1, type: "text" },
    { id: 41, text: " ", line: 1, type: "whitespace" },
    { id: 42, text: "the", line: 1, type: "text" },
    { id: 43, text: " ", line: 1, type: "whitespace" },
    { id: 44, text: "blood.", line: 1, type: "text" },
  ],
  mappings: [
    {
      id: "fa59c59e-0744-4995-9dc9-02100212e04e",
      sourceTokenIds: [0],
      targetTokenIds: [4, 2],
    },
    {
      id: "46f5d079-b761-4cd3-a380-cd09899a33f6",
      sourceTokenIds: [1],
      targetTokenIds: [6, 8, 10],
    },
    {
      id: "4fbc5e79-dd26-4dea-9ea4-d21ae32718d1",
      sourceTokenIds: [2],
      targetTokenIds: [12],
    },
    {
      id: "11f5de84-61f8-4bf7-bf8a-3cd92159b0a5",
      sourceTokenIds: [5],
      targetTokenIds: [14],
    },
    {
      id: "b4b16816-adf8-4d14-8ffa-3b1f932abb0b",
      sourceTokenIds: [4],
      targetTokenIds: [16, 18],
    },
    {
      id: "34b4516e-e210-4106-9d1f-d9592d9be659",
      sourceTokenIds: [3],
      targetTokenIds: [24, 26, 22],
    },
    {
      id: "0dd769ec-7a03-4657-be25-bd88f870e4c9",
      sourceTokenIds: [7],
      targetTokenIds: [28, 30],
    },
    {
      id: "2f0c5e31-8f89-4224-9b96-8177187901af",
      sourceTokenIds: [8],
      targetTokenIds: [34, 32],
    },
    {
      id: "10e245a2-28f3-4752-88fb-65831484705a",
      sourceTokenIds: [10],
      targetTokenIds: [36, 38],
    },
    {
      id: "12846ffd-b2c4-4847-ba40-ddec8fa823a6",
      sourceTokenIds: [11, 13],
      targetTokenIds: [40],
    },
    {
      id: "e4c9fa69-1320-4138-84c9-1be4fbc6e474",
      sourceTokenIds: [12],
      targetTokenIds: [42, 44],
    },
  ],
} satisfies QuoteSlicerExport;
