import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001eQ01DawnLight = {
  attestation: {
    tokens: [
      { id: 0, text: "明", pinyin: "ming2", type: "character" },
      { id: 1, text: "也", pinyin: "ye3", type: "character" },
      { id: 2, text: "。", pinyin: null, type: "punctuation" },
      { id: 3, text: "从", pinyin: "cong2", type: "character" },
      { id: 4, text: "日", pinyin: "ri4", type: "character" },
      { id: 5, text: "見", pinyin: "jian4", type: "character" },
      { id: 6, text: "一", pinyin: "yi1", type: "character" },
      { id: 7, text: "上", pinyin: "shang4", type: "character" },
      { id: 8, text: "。", pinyin: null, type: "punctuation" },
      { id: 9, text: "一", pinyin: "yi1", type: "character" },
      { id: 10, text: "，", pinyin: null, type: "punctuation" },
      { id: 11, text: "地", pinyin: "di4", type: "character" },
      { id: 12, text: "也", pinyin: "ye3", type: "character" },
      { id: 13, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "It", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "is", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "light.", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "From", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "日", type: "hanzi" },
      { id: 9, text: ",", type: "punctuation" },
      { id: 10, text: " ", type: "whitespace" },
      { id: 11, text: "as", type: "text" },
      { id: 12, text: " ", type: "whitespace" },
      { id: 13, text: "seen", type: "text" },
      { id: 14, text: " ", type: "whitespace" },
      { id: 15, text: "above", type: "text" },
      { id: 16, text: " ", type: "whitespace" },
      { id: 17, text: "a", type: "text" },
      { id: 18, text: " ", type: "whitespace" },
      { id: 19, text: "line.", type: "text" },
      { id: 20, text: " ", type: "whitespace" },
      { id: 21, text: "The", type: "text" },
      { id: 22, text: " ", type: "whitespace" },
      { id: 23, text: "stroke", type: "text" },
      { id: 24, text: " ", type: "whitespace" },
      { id: 25, text: "is", type: "text" },
      { id: 26, text: " ", type: "whitespace" },
      { id: 27, text: "the", type: "text" },
      { id: 28, text: " ", type: "whitespace" },
      { id: 29, text: "ground.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "aa69f08d-9687-4250-9399-e5ce4160f09b",
        sourceTokenIds: [0],
        targetTokenIds: [4],
      },
      {
        id: "5b66e3f2-6eb9-4b4a-aa2d-10a5f0da097a",
        sourceTokenIds: [1],
        targetTokenIds: [2, 0],
      },
      {
        id: "78bc006d-996d-4961-b919-e5b501211fff",
        sourceTokenIds: [3],
        targetTokenIds: [6],
      },
      {
        id: "0d1c9222-8495-4942-bcde-7b5b0e8d9581",
        sourceTokenIds: [4],
        targetTokenIds: [8],
      },
      {
        id: "f9adde21-9e43-46e7-97f8-e6bffad98d36",
        sourceTokenIds: [5],
        targetTokenIds: [13],
      },
      {
        id: "b89c599b-4b38-49f3-9cae-c370305b63d2",
        sourceTokenIds: [6],
        targetTokenIds: [19, 17],
      },
      {
        id: "834c39a5-9607-4b07-ba14-8567be74d0c4",
        sourceTokenIds: [7],
        targetTokenIds: [15],
      },
      {
        id: "fec6c57d-d026-4890-981e-cc9db66427dd",
        sourceTokenIds: [9],
        targetTokenIds: [23, 21],
      },
      {
        id: "5ac82741-d72d-4c9c-9d08-9becb398d36a",
        sourceTokenIds: [11],
        targetTokenIds: [29, 27],
      },
      {
        id: "91e3f7aa-5f00-4c76-b6f2-afea36067eaf",
        sourceTokenIds: [12],
        targetTokenIds: [25],
      },
    ],
    breaks: {
      attestation: [],
      translation: [],
    },
  },
} satisfies AttestationTranslationAlignment;
