import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001jQ03VitalEnergy = {
  attestation: {
    tokens: [
      { id: 0, text: "少", pinyin: "shao3", type: "character" },
      { id: 1, text: "之", pinyin: "zhi1", type: "character" },
      { id: 2, text: "時", pinyin: "shi2", type: "character" },
      { id: 3, text: "，", pinyin: null, type: "punctuation" },
      { id: 4, text: "血", pinyin: "xue4", type: "character" },
      { id: 5, text: "氣", pinyin: "qi4", type: "character" },
      { id: 6, text: "未", pinyin: "wei4", type: "character" },
      { id: 7, text: "定", pinyin: "ding4", type: "character" },
      { id: 8, text: "及", pinyin: "ji2", type: "character" },
      { id: 9, text: "其", pinyin: "qi2", type: "character" },
      { id: 10, text: "壯", pinyin: "zhuang4", type: "character" },
      { id: 11, text: "也", pinyin: undefined, type: "character" },
      { id: 12, text: "，", pinyin: null, type: "punctuation" },
      { id: 13, text: "血", pinyin: "xue4", type: "character" },
      { id: 14, text: "氣", pinyin: "qi4", type: "character" },
      { id: 15, text: "方", pinyin: "fang1", type: "character" },
      { id: 16, text: "剛", pinyin: "gang1", type: "character" },
      { id: 17, text: "及", pinyin: "ji2", type: "character" },
      { id: 18, text: "其", pinyin: "qi2", type: "character" },
      { id: 19, text: "老", pinyin: "lao3", type: "character" },
      { id: 20, text: "也", pinyin: undefined, type: "character" },
      { id: 21, text: "，", pinyin: null, type: "punctuation" },
      { id: 22, text: "血", pinyin: "xue4", type: "character" },
      { id: 23, text: "氣", pinyin: "qi4", type: "character" },
      { id: 24, text: "既", pinyin: "ji4", type: "character" },
      { id: 25, text: "衰", pinyin: "shuai1", type: "character" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "At", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "the", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "time", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "of", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "youth,", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "blood", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "and", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "vital", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "energy", type: "text" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "are", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "not", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "yet", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "settled;", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "reaching", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "one's", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "maturity,", type: "text" },
      { id: 31, text: " ", type: "whitespace" },
      { id: 32, text: "blood", type: "text" },
      { id: 33, text: " ", type: "whitespace" },
      { id: 34, text: "and", type: "text" },
      { id: 35, text: " ", type: "whitespace" },
      { id: 36, text: "vital", type: "text" },
      { id: 37, text: " ", type: "whitespace" },
      { id: 38, text: "energy", type: "text" },
      { id: 39, text: " ", type: "whitespace" },
      { id: 40, text: "are", type: "text" },
      { id: 41, text: " ", type: "whitespace" },
      { id: 42, text: "then", type: "text" },
      { id: 43, text: " ", type: "whitespace" },
      { id: 44, text: "strong;", type: "text" },
      { id: 45, text: " ", type: "whitespace" },
      { id: 46, text: "reaching", type: "text" },
      { id: 47, text: " ", type: "whitespace" },
      { id: 48, text: "one's", type: "text" },
      { id: 49, text: " ", type: "whitespace" },
      { id: 50, text: "seniority,", type: "text" },
      { id: 51, text: " ", type: "whitespace" },
      { id: 52, text: "blood", type: "text" },
      { id: 53, text: " ", type: "whitespace" },
      { id: 54, text: "and", type: "text" },
      { id: 55, text: " ", type: "whitespace" },
      { id: 56, text: "vital", type: "text" },
      { id: 57, text: " ", type: "whitespace" },
      { id: 58, text: "energy", type: "text" },
      { id: 59, text: " ", type: "whitespace" },
      { id: 60, text: "have", type: "text" },
      { id: 61, text: " ", type: "whitespace" },
      { id: 62, text: "already", type: "text" },
      { id: 63, text: " ", type: "whitespace" },
      { id: 64, text: "declined.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "818ba0f6-32a6-4910-9066-4ec7a4bfa34b",
        sourceTokenIds: [0],
        targetTokenIds: [8],
      },
      {
        id: "0d8e91c8-32a4-4c6a-9f41-0ecde1e65db1",
        sourceTokenIds: [1],
        targetTokenIds: [6],
      },
      {
        id: "402eef06-dd6f-4e25-9c7f-1f980ad0336f",
        sourceTokenIds: [2],
        targetTokenIds: [4],
      },
      {
        id: "ad58f8a0-387d-419f-a603-8fab73ad2c63",
        sourceTokenIds: [4],
        targetTokenIds: [10],
      },
      {
        id: "643d8fec-5873-4a82-bdd9-5dda4a0a05c1",
        sourceTokenIds: [5],
        targetTokenIds: [14, 16],
      },
      {
        id: "2561340b-61dc-4e6b-849c-c67c7bc4ccdd",
        sourceTokenIds: [6],
        targetTokenIds: [22, 20],
      },
      {
        id: "65494b4a-b98a-4f55-807b-a29a7cf1ff28",
        sourceTokenIds: [7],
        targetTokenIds: [24],
      },
      {
        id: "88bc4e94-488c-4429-a2ef-42015a9260d7",
        sourceTokenIds: [8],
        targetTokenIds: [26],
      },
      {
        id: "2bf8d582-8302-4724-bc50-01a08be9b567",
        sourceTokenIds: [9],
        targetTokenIds: [28],
      },
      {
        id: "b70d6464-c642-4db6-8240-719d8f86c5f1",
        sourceTokenIds: [10],
        targetTokenIds: [30],
      },
      {
        id: "652adc8a-7f32-48e3-918c-836bb4387d0b",
        sourceTokenIds: [13],
        targetTokenIds: [32],
      },
      {
        id: "527b343c-2c45-4e41-9d87-27ca3d04e678",
        sourceTokenIds: [14],
        targetTokenIds: [38, 36],
      },
      {
        id: "28df17b4-8086-40fd-8b34-e738b6939a14",
        sourceTokenIds: [15],
        targetTokenIds: [42],
      },
      {
        id: "993098e2-8e98-4fc6-b9d5-08a840d5cffc",
        sourceTokenIds: [16],
        targetTokenIds: [44],
      },
      {
        id: "51873ccf-12fe-419d-ac03-03cf2d8486c0",
        sourceTokenIds: [17],
        targetTokenIds: [46],
      },
      {
        id: "8bf9366a-83b6-4de6-8492-ae2628868dc2",
        sourceTokenIds: [18],
        targetTokenIds: [48],
      },
      {
        id: "862bb97e-bf5a-4ab6-9f10-83be242180db",
        sourceTokenIds: [19],
        targetTokenIds: [50],
      },
      {
        id: "cc8fc609-6ac2-4055-bc78-be90342cb1ca",
        sourceTokenIds: [22],
        targetTokenIds: [52],
      },
      {
        id: "f847919f-8bc3-4013-8851-a6a370fb6fc8",
        sourceTokenIds: [23],
        targetTokenIds: [58, 56],
      },
      {
        id: "ff40403f-f899-4fdb-bd55-5765c55b14ca",
        sourceTokenIds: [24],
        targetTokenIds: [62],
      },
      {
        id: "1a62ecc6-770b-4b04-a453-7e66e3a2edd4",
        sourceTokenIds: [25],
        targetTokenIds: [64],
      },
    ],
    breaks: {
      attestation: [8, 17],
      translation: [26, 46],
    },
  },
} satisfies AttestationTranslationAlignment;
