import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001gQ01TreeBottom = {
  attestation: {
    tokens: [
      { id: 0, text: "木", pinyin: "mu4", type: "character" },
      { id: 1, text: "下", pinyin: "xia4", type: "character" },
      { id: 2, text: "曰", pinyin: "yue1", type: "character" },
      { id: 3, text: "本", pinyin: "ben3", type: "character" },
      { id: 4, text: "。", pinyin: null, type: "punctuation" },
      { id: 5, text: "从", pinyin: "cong2", type: "character" },
      { id: 6, text: "木", pinyin: "mu4", type: "character" },
      { id: 7, text: "，", pinyin: null, type: "punctuation" },
      { id: 8, text: "一", pinyin: "yi1", type: "character" },
      { id: 9, text: "在", pinyin: "zai4", type: "character" },
      { id: 10, text: "其", pinyin: "qi2", type: "character" },
      { id: 11, text: "下", pinyin: "xia4", type: "character" },
      { id: 12, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "The", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "bottom", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "of", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "a", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "tree", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "is", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "called", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "本", type: "hanzi" },
      { id: 15, text: ".", type: "punctuation" },
      { id: 16, text: " ", type: "whitespace" },
      { id: 17, text: "From", type: "text" },
      { id: 18, text: " ", type: "whitespace" },
      { id: 19, text: "木", type: "hanzi" },
      { id: 20, text: ",", type: "punctuation" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "a", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "stroke", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "is", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "beneath", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "it.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "218cb626-aaab-487e-b00e-18be7ad93f58",
        sourceTokenIds: [0],
        targetTokenIds: [8, 6],
      },
      {
        id: "aa263e37-59df-4ac3-b961-b946d39984d4",
        sourceTokenIds: [1],
        targetTokenIds: [0, 2],
      },
      {
        id: "c60a0bba-d81c-41da-ac68-65fbe6be8783",
        sourceTokenIds: [2],
        targetTokenIds: [10, 12],
      },
      {
        id: "a0742c91-d756-4541-bcba-0bce51cf7313",
        sourceTokenIds: [5],
        targetTokenIds: [17],
      },
      {
        id: "c886a070-a43d-4382-9ea4-5d951bbf0c41",
        sourceTokenIds: [6],
        targetTokenIds: [19],
      },
      {
        id: "a0c11dbc-0d99-4254-9b59-a25220b88256",
        sourceTokenIds: [3],
        targetTokenIds: [14],
      },
      {
        id: "6bf6b038-c892-4ce6-94bc-23180cfca11e",
        sourceTokenIds: [8],
        targetTokenIds: [24, 22],
      },
      {
        id: "0cfd17cf-8a19-4a92-b835-73f92e6b7f32",
        sourceTokenIds: [9],
        targetTokenIds: [26],
      },
      {
        id: "bca29d44-620f-42bb-8592-6c2a0251792a",
        sourceTokenIds: [11],
        targetTokenIds: [28],
      },
      {
        id: "f0256b08-d0e8-488a-836a-848b43e49624",
        sourceTokenIds: [10],
        targetTokenIds: [30],
      },
    ],
    breaks: {
      attestation: [],
      translation: [17],
    },
  },
} satisfies AttestationTranslationAlignment;
