import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001jQ01SacrificialBlood = {
  attestation: {
    tokens: [
      { id: 0, text: "祭", pinyin: "ji4", type: "character" },
      { id: 1, text: "所", pinyin: "suo3", type: "character" },
      { id: 2, text: "薦", pinyin: "jian4", type: "character" },
      { id: 3, text: "牲", pinyin: "sheng1", type: "character" },
      { id: 4, text: "血", pinyin: "xue4", type: "character" },
      { id: 5, text: "也", pinyin: "ye3", type: "character" },
      { id: 6, text: "。", pinyin: null, type: "punctuation" },
      { id: 7, text: "从", pinyin: "cong2", type: "character" },
      { id: 8, text: "皿", pinyin: "min3", type: "character" },
      { id: 9, text: "，", pinyin: null, type: "punctuation" },
      { id: 10, text: "一", pinyin: "yi1", type: "character" },
      { id: 11, text: "象", pinyin: "xiang4", type: "character" },
      { id: 12, text: "血", pinyin: "xue4", type: "character" },
      { id: 13, text: "形", pinyin: "xing2", type: "character" },
      { id: 14, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "At", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "a", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "sacrifice,", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "that", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "which", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "is", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "presented", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "is", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "the", type: "text" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "blood", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "of", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "the", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "sacrificial", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "victim.", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "Formed", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "from", type: "text" },
      { id: 31, text: " ", type: "whitespace" },
      { id: 32, text: "a", type: "text" },
      { id: 33, text: " ", type: "whitespace" },
      { id: 34, text: "vessel;", type: "text" },
      { id: 35, text: " ", type: "whitespace" },
      { id: 36, text: "the", type: "text" },
      { id: 37, text: " ", type: "whitespace" },
      { id: 38, text: "stroke", type: "text" },
      { id: 39, text: " ", type: "whitespace" },
      { id: 40, text: "depicts", type: "text" },
      { id: 41, text: " ", type: "whitespace" },
      { id: 42, text: "the", type: "text" },
      { id: 43, text: " ", type: "whitespace" },
      { id: 44, text: "blood.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "fa59c59e-0744-4995-9dc9-02100212e04e",
        sourceTokenIds: [0],
        targetTokenIds: [4, 2],
      },
      {
        id: "46f5d079-b761-4cd3-a380-cd09899a33f6",
        sourceTokenIds: [1],
        targetTokenIds: [6, 8, 10],
      },
      {
        id: "4fbc5e79-dd26-4dea-9ea4-d21ae32718d1",
        sourceTokenIds: [2],
        targetTokenIds: [12],
      },
      {
        id: "11f5de84-61f8-4bf7-bf8a-3cd92159b0a5",
        sourceTokenIds: [5],
        targetTokenIds: [14],
      },
      {
        id: "b4b16816-adf8-4d14-8ffa-3b1f932abb0b",
        sourceTokenIds: [4],
        targetTokenIds: [16, 18],
      },
      {
        id: "34b4516e-e210-4106-9d1f-d9592d9be659",
        sourceTokenIds: [3],
        targetTokenIds: [24, 26, 22],
      },
      {
        id: "0dd769ec-7a03-4657-be25-bd88f870e4c9",
        sourceTokenIds: [7],
        targetTokenIds: [28, 30],
      },
      {
        id: "2f0c5e31-8f89-4224-9b96-8177187901af",
        sourceTokenIds: [8],
        targetTokenIds: [34, 32],
      },
      {
        id: "10e245a2-28f3-4752-88fb-65831484705a",
        sourceTokenIds: [10],
        targetTokenIds: [36, 38],
      },
      {
        id: "12846ffd-b2c4-4847-ba40-ddec8fa823a6",
        sourceTokenIds: [11, 13],
        targetTokenIds: [40],
      },
      {
        id: "e4c9fa69-1320-4138-84c9-1be4fbc6e474",
        sourceTokenIds: [12],
        targetTokenIds: [42, 44],
      },
    ],
    breaks: {
      attestation: [7],
      translation: [28],
    },
  },
} satisfies AttestationTranslationAlignment;
