import type { AttestationTranslationAlignment } from "../../quote-slicer-export";

export const l001cQ04MandateFromHeaven = {
  attestation: {
    tokens: [
      { id: 0, text: "天", pinyin: "tian1", type: "character" },
      { id: 1, text: "子", pinyin: "zi3", type: "character" },
      { id: 2, text: "受", pinyin: "shou4", type: "character" },
      { id: 3, text: "命", pinyin: "ming4", type: "character" },
      { id: 4, text: "於", pinyin: "yu2", type: "character" },
      { id: 5, text: "天", pinyin: "tian1", type: "character" },
      { id: 6, text: "，", pinyin: null, type: "punctuation" },
      { id: 7, text: "諸", pinyin: "zhu1", type: "character" },
      { id: 8, text: "侯", pinyin: "hou2", type: "character" },
      { id: 9, text: "受", pinyin: "shou4", type: "character" },
      { id: 10, text: "命", pinyin: "ming4", type: "character" },
      { id: 11, text: "於", pinyin: "yu2", type: "character" },
      { id: 12, text: "天", pinyin: "tian1", type: "character" },
      { id: 13, text: "子", pinyin: "zi3", type: "character" },
      { id: 14, text: "，", pinyin: null, type: "punctuation" },
      { id: 15, text: "子", pinyin: "zi3", type: "character" },
      { id: 16, text: "受", pinyin: "shou4", type: "character" },
      { id: 17, text: "命", pinyin: "ming4", type: "character" },
      { id: 18, text: "於", pinyin: "yu2", type: "character" },
      { id: 19, text: "父", pinyin: "fu4", type: "character" },
      { id: 20, text: "，", pinyin: null, type: "punctuation" },
      { id: 21, text: "臣", pinyin: "chen2", type: "character" },
      { id: 22, text: "妾", pinyin: "qie4", type: "character" },
      { id: 23, text: "受", pinyin: "shou4", type: "character" },
      { id: 24, text: "命", pinyin: "ming4", type: "character" },
      { id: 25, text: "於", pinyin: "yu2", type: "character" },
      { id: 26, text: "君", pinyin: "jun1", type: "character" },
      { id: 27, text: "，", pinyin: null, type: "punctuation" },
      { id: 28, text: "妻", pinyin: "qi1", type: "character" },
      { id: 29, text: "受", pinyin: "shou4", type: "character" },
      { id: 30, text: "命", pinyin: "ming4", type: "character" },
      { id: 31, text: "於", pinyin: "yu2", type: "character" },
      { id: 32, text: "夫", pinyin: "fu1", type: "character" },
      { id: 33, text: "。", pinyin: null, type: "punctuation" },
      { id: 34, text: "諸", pinyin: "zhu1", type: "character" },
      { id: 35, text: "所", pinyin: "suo3", type: "character" },
      { id: 36, text: "受", pinyin: "shou4", type: "character" },
      { id: 37, text: "命", pinyin: "ming4", type: "character" },
      { id: 38, text: "者", pinyin: "zhe3", type: "character" },
      { id: 39, text: "，", pinyin: null, type: "punctuation" },
      { id: 40, text: "其", pinyin: "qi2", type: "character" },
      { id: 41, text: "尊", pinyin: "zun1", type: "character" },
      { id: 42, text: "皆", pinyin: "jie1", type: "character" },
      { id: 43, text: "天", pinyin: "tian1", type: "character" },
      { id: 44, text: "也", pinyin: "ye3", type: "character" },
      { id: 45, text: "，", pinyin: null, type: "punctuation" },
      { id: 46, text: "雖", pinyin: "sui1", type: "character" },
      { id: 47, text: "謂", pinyin: "wei4", type: "character" },
      { id: 48, text: "受", pinyin: "shou4", type: "character" },
      { id: 49, text: "命", pinyin: "ming4", type: "character" },
      { id: 50, text: "於", pinyin: "yu2", type: "character" },
      { id: 51, text: "天", pinyin: "tian1", type: "character" },
      { id: 52, text: "亦", pinyin: "yi4", type: "character" },
      { id: 53, text: "可", pinyin: "ke3", type: "character" },
      { id: 54, text: "。", pinyin: null, type: "punctuation" },
    ],
  },
  translation: {
    tokens: [
      { id: 0, text: "The", type: "text" },
      { id: 1, text: " ", type: "whitespace" },
      { id: 2, text: "Son", type: "text" },
      { id: 3, text: " ", type: "whitespace" },
      { id: 4, text: "of", type: "text" },
      { id: 5, text: " ", type: "whitespace" },
      { id: 6, text: "Heaven", type: "text" },
      { id: 7, text: " ", type: "whitespace" },
      { id: 8, text: "receives", type: "text" },
      { id: 9, text: " ", type: "whitespace" },
      { id: 10, text: "his", type: "text" },
      { id: 11, text: " ", type: "whitespace" },
      { id: 12, text: "mandate", type: "text" },
      { id: 13, text: " ", type: "whitespace" },
      { id: 14, text: "from", type: "text" },
      { id: 15, text: " ", type: "whitespace" },
      { id: 16, text: "Heaven;", type: "text" },
      { id: 17, text: " ", type: "whitespace" },
      { id: 18, text: "the", type: "text" },
      { id: 19, text: " ", type: "whitespace" },
      { id: 20, text: "feudal", type: "text" },
      { id: 21, text: " ", type: "whitespace" },
      { id: 22, text: "lords", type: "text" },
      { id: 23, text: " ", type: "whitespace" },
      { id: 24, text: "receive", type: "text" },
      { id: 25, text: " ", type: "whitespace" },
      { id: 26, text: "their", type: "text" },
      { id: 27, text: " ", type: "whitespace" },
      { id: 28, text: "mandates", type: "text" },
      { id: 29, text: " ", type: "whitespace" },
      { id: 30, text: "from", type: "text" },
      { id: 31, text: " ", type: "whitespace" },
      { id: 32, text: "the", type: "text" },
      { id: 33, text: " ", type: "whitespace" },
      { id: 34, text: "Son", type: "text" },
      { id: 35, text: " ", type: "whitespace" },
      { id: 36, text: "of", type: "text" },
      { id: 37, text: " ", type: "whitespace" },
      { id: 38, text: "Heaven;", type: "text" },
      { id: 39, text: " ", type: "whitespace" },
      { id: 40, text: "a", type: "text" },
      { id: 41, text: " ", type: "whitespace" },
      { id: 42, text: "son", type: "text" },
      { id: 43, text: " ", type: "whitespace" },
      { id: 44, text: "receives", type: "text" },
      { id: 45, text: " ", type: "whitespace" },
      { id: 46, text: "commands", type: "text" },
      { id: 47, text: " ", type: "whitespace" },
      { id: 48, text: "from", type: "text" },
      { id: 49, text: " ", type: "whitespace" },
      { id: 50, text: "his", type: "text" },
      { id: 51, text: " ", type: "whitespace" },
      { id: 52, text: "father;", type: "text" },
      { id: 53, text: " ", type: "whitespace" },
      { id: 54, text: "subjects", type: "text" },
      { id: 55, text: " ", type: "whitespace" },
      { id: 56, text: "and", type: "text" },
      { id: 57, text: " ", type: "whitespace" },
      { id: 58, text: "concubines", type: "text" },
      { id: 59, text: " ", type: "whitespace" },
      { id: 60, text: "receive", type: "text" },
      { id: 61, text: " ", type: "whitespace" },
      { id: 62, text: "commands", type: "text" },
      { id: 63, text: " ", type: "whitespace" },
      { id: 64, text: "from", type: "text" },
      { id: 65, text: " ", type: "whitespace" },
      { id: 66, text: "their", type: "text" },
      { id: 67, text: " ", type: "whitespace" },
      { id: 68, text: "lord;", type: "text" },
      { id: 69, text: " ", type: "whitespace" },
      { id: 70, text: "a", type: "text" },
      { id: 71, text: " ", type: "whitespace" },
      { id: 72, text: "wife", type: "text" },
      { id: 73, text: " ", type: "whitespace" },
      { id: 74, text: "receives", type: "text" },
      { id: 75, text: " ", type: "whitespace" },
      { id: 76, text: "commands", type: "text" },
      { id: 77, text: " ", type: "whitespace" },
      { id: 78, text: "from", type: "text" },
      { id: 79, text: " ", type: "whitespace" },
      { id: 80, text: "her", type: "text" },
      { id: 81, text: " ", type: "whitespace" },
      { id: 82, text: "husband.", type: "text" },
      { id: 83, text: " ", type: "whitespace" },
      { id: 84, text: "As", type: "text" },
      { id: 85, text: " ", type: "whitespace" },
      { id: 86, text: "for", type: "text" },
      { id: 87, text: " ", type: "whitespace" },
      { id: 88, text: "all", type: "text" },
      { id: 89, text: " ", type: "whitespace" },
      { id: 90, text: "those", type: "text" },
      { id: 91, text: " ", type: "whitespace" },
      { id: 92, text: "from", type: "text" },
      { id: 93, text: " ", type: "whitespace" },
      { id: 94, text: "whom", type: "text" },
      { id: 95, text: " ", type: "whitespace" },
      { id: 96, text: "decrees", type: "text" },
      { id: 97, text: " ", type: "whitespace" },
      { id: 98, text: "are", type: "text" },
      { id: 99, text: " ", type: "whitespace" },
      { id: 100, text: "received,", type: "text" },
      { id: 101, text: " ", type: "whitespace" },
      { id: 102, text: "their", type: "text" },
      { id: 103, text: " ", type: "whitespace" },
      { id: 104, text: "superior", type: "text" },
      { id: 105, text: " ", type: "whitespace" },
      { id: 106, text: "is,", type: "text" },
      { id: 107, text: " ", type: "whitespace" },
      { id: 108, text: "in", type: "text" },
      { id: 109, text: " ", type: "whitespace" },
      { id: 110, text: "all", type: "text" },
      { id: 111, text: " ", type: "whitespace" },
      { id: 112, text: "cases,", type: "text" },
      { id: 113, text: " ", type: "whitespace" },
      { id: 114, text: "Heaven.", type: "text" },
      { id: 115, text: " ", type: "whitespace" },
      { id: 116, text: "Even", type: "text" },
      { id: 117, text: " ", type: "whitespace" },
      { id: 118, text: "stating", type: "text" },
      { id: 119, text: " ", type: "whitespace" },
      { id: 120, text: "they", type: "text" },
      { id: 121, text: " ", type: "whitespace" },
      { id: 122, text: "receive", type: "text" },
      { id: 123, text: " ", type: "whitespace" },
      { id: 124, text: "their", type: "text" },
      { id: 125, text: " ", type: "whitespace" },
      { id: 126, text: "allotment", type: "text" },
      { id: 127, text: " ", type: "whitespace" },
      { id: 128, text: "from", type: "text" },
      { id: 129, text: " ", type: "whitespace" },
      { id: 130, text: "Heaven", type: "text" },
      { id: 131, text: " ", type: "whitespace" },
      { id: 132, text: "is", type: "text" },
      { id: 133, text: " ", type: "whitespace" },
      { id: 134, text: "also", type: "text" },
      { id: 135, text: " ", type: "whitespace" },
      { id: 136, text: "acceptable.", type: "text" },
    ],
  },
  alignment: {
    mappings: [
      {
        id: "1deae428-8699-4cf9-bbd7-9854af8ca8fd",
        sourceTokenIds: [0, 1],
        targetTokenIds: [0, 2, 4, 6],
      },
      {
        id: "2189fab9-1643-49a1-8a28-88dfaea2ab96",
        sourceTokenIds: [2],
        targetTokenIds: [8],
      },
      {
        id: "8f373eac-bbb4-46df-ad90-160a748f78ac",
        sourceTokenIds: [3],
        targetTokenIds: [12],
      },
      {
        id: "bdbebcb6-d352-4795-b7b8-0a5063fefa3c",
        sourceTokenIds: [4],
        targetTokenIds: [14],
      },
      {
        id: "0a8bcb6c-4eff-492a-8566-0d4f57074cb9",
        sourceTokenIds: [5],
        targetTokenIds: [16],
      },
      {
        id: "cf57331f-c84d-45d1-af29-2cde9b1a44c2",
        sourceTokenIds: [7, 8],
        targetTokenIds: [18, 20, 22],
      },
      {
        id: "d6fa0483-13e8-4033-bff1-fe1058221867",
        sourceTokenIds: [9],
        targetTokenIds: [24],
      },
      {
        id: "36f747a3-fb7e-4756-9d3a-98be60716a35",
        sourceTokenIds: [10],
        targetTokenIds: [28],
      },
      {
        id: "98462d6a-32e6-4566-964c-8e26b032a1be",
        sourceTokenIds: [11],
        targetTokenIds: [30],
      },
      {
        id: "b75de290-4412-4607-9f78-dd40756f397a",
        sourceTokenIds: [12, 13],
        targetTokenIds: [32, 34, 36, 38],
      },
      {
        id: "cb7e27af-a948-44e2-bec1-d2d291f34523",
        sourceTokenIds: [15],
        targetTokenIds: [40, 42],
      },
      {
        id: "3305fdb0-957b-4b6d-baef-a916fc6360d9",
        sourceTokenIds: [16],
        targetTokenIds: [44],
      },
      {
        id: "9f89bfe8-ccf9-4648-b261-2e1c07801cc3",
        sourceTokenIds: [17],
        targetTokenIds: [46],
      },
      {
        id: "dc4028ec-bbea-4ef4-b2bd-03979c343b01",
        sourceTokenIds: [18],
        targetTokenIds: [48],
      },
      {
        id: "62f10c72-5a77-41b5-b614-363a25a5510c",
        sourceTokenIds: [19],
        targetTokenIds: [52],
      },
      {
        id: "cd83eca9-92a1-4b4a-9fe8-3a06308cbf6f",
        sourceTokenIds: [21],
        targetTokenIds: [54],
      },
      {
        id: "02bc24b7-effc-4ce5-b8f4-f0f6f27bda87",
        sourceTokenIds: [22],
        targetTokenIds: [58],
      },
      {
        id: "e148a85a-e037-49a9-a43c-db36ff0c1816",
        sourceTokenIds: [23],
        targetTokenIds: [60],
      },
      {
        id: "2900e1c0-5547-4c6b-9462-7bbeed4f82b7",
        sourceTokenIds: [24],
        targetTokenIds: [62],
      },
      {
        id: "24a088db-7f4e-4748-ae22-7f22bf4924f3",
        sourceTokenIds: [25],
        targetTokenIds: [64],
      },
      {
        id: "ccf44f7d-444d-4354-99ac-34f44f14020d",
        sourceTokenIds: [26],
        targetTokenIds: [68],
      },
      {
        id: "47446209-5a11-4c1f-89b8-e65ecb6f6993",
        sourceTokenIds: [28],
        targetTokenIds: [70, 72],
      },
      {
        id: "fb16c2c4-ef9a-4d8a-849f-2811da323a82",
        sourceTokenIds: [29],
        targetTokenIds: [74],
      },
      {
        id: "76f83eb3-7619-4708-8b9d-9364496af247",
        sourceTokenIds: [30],
        targetTokenIds: [76],
      },
      {
        id: "5c6a7d64-6a9a-4d3c-952b-b080b431ba57",
        sourceTokenIds: [31],
        targetTokenIds: [78],
      },
      {
        id: "0fe16b9c-6921-4e61-99ea-d7eec716a309",
        sourceTokenIds: [32],
        targetTokenIds: [82],
      },
      {
        id: "6f0901fa-8b99-47c7-a3f0-b45d598496a5",
        sourceTokenIds: [34],
        targetTokenIds: [88],
      },
      {
        id: "7b1682f3-2bb0-4f36-ad58-2ae176bb3091",
        sourceTokenIds: [35],
        targetTokenIds: [92, 94],
      },
      {
        id: "f4b54e03-913e-4a4f-9265-858edc8def6c",
        sourceTokenIds: [38],
        targetTokenIds: [84, 86, 90],
      },
      {
        id: "8c499a49-f263-40c1-a9ef-2ff22ab87e9a",
        sourceTokenIds: [36],
        targetTokenIds: [100],
      },
      {
        id: "28c0e409-4be9-4f28-91a7-3073835b212a",
        sourceTokenIds: [37],
        targetTokenIds: [96],
      },
      {
        id: "95554878-ea27-41a0-ad6e-f3b78dce98f7",
        sourceTokenIds: [40],
        targetTokenIds: [102],
      },
      {
        id: "d1c13015-a78c-450d-9239-d8e82a5c2acd",
        sourceTokenIds: [41],
        targetTokenIds: [104],
      },
      {
        id: "b542203e-cad8-4b05-bf8d-a8edaedac1d1",
        sourceTokenIds: [42],
        targetTokenIds: [108, 110, 112],
      },
      {
        id: "ea042f27-a3fa-483b-bdfc-0177029779fb",
        sourceTokenIds: [44],
        targetTokenIds: [106],
      },
      {
        id: "0839187e-eb36-4edd-8dd2-b17c5348c30a",
        sourceTokenIds: [43],
        targetTokenIds: [114],
      },
      {
        id: "b9169cf0-a454-4972-8a12-4d8d8c4f8fc9",
        sourceTokenIds: [46],
        targetTokenIds: [116],
      },
      {
        id: "3592b016-b352-4d7d-887b-71f776ac5085",
        sourceTokenIds: [47],
        targetTokenIds: [118],
      },
      {
        id: "6288abe6-2308-48b4-a77c-fdd512e93fb4",
        sourceTokenIds: [48],
        targetTokenIds: [122],
      },
      {
        id: "a50366b9-87b3-4eab-a073-ad70babca89c",
        sourceTokenIds: [49],
        targetTokenIds: [126],
      },
      {
        id: "91b9c5db-adcb-4d01-9487-2fd86cc2531a",
        sourceTokenIds: [50],
        targetTokenIds: [128],
      },
      {
        id: "8b14505a-6bed-41ed-ae9d-f9dc8001282c",
        sourceTokenIds: [51],
        targetTokenIds: [130],
      },
      {
        id: "30e9afa1-9217-4c65-b842-4d68642ae167",
        sourceTokenIds: [52],
        targetTokenIds: [134],
      },
      {
        id: "9ecd714c-f955-4c76-baa9-4f589e65ea68",
        sourceTokenIds: [53],
        targetTokenIds: [136],
      },
    ],
    breaks: {
      attestation: [21, 34],
      translation: [18, 40, 54, 70, 84, 116],
    },
  },
} satisfies AttestationTranslationAlignment;
