import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const shuowenJieziOnXue = {
  meta: {
    sourceText: "祭所薦牲血也。从皿，一象血形。",
    targetText:
      "The blood of a sacrificial animal, offered in sacrifice. Formed from a vessel; the stroke depicts the blood.",
    provenance: "Shuowen Jiezi",
  },
  sourceTokens: [
    { id: 0, text: "祭", pinyin: "ji4", line: 0, type: "character" },
    { id: 1, text: "所", pinyin: undefined, line: 0, type: "character" },
    { id: 2, text: "薦", pinyin: "jian4", line: 0, type: "character" },
    { id: 3, text: "牲", pinyin: "sheng1", line: 0, type: "character" },
    { id: 4, text: "血", pinyin: "xue4", line: 0, type: "character" },
    { id: 5, text: "也", pinyin: undefined, line: 0, type: "character" },
    { id: 6, text: "。", pinyin: null, line: 0, type: "punctuation" },
    { id: 7, text: "从", pinyin: "cong2", line: 1, type: "character" },
    { id: 8, text: "皿", pinyin: "min3", line: 1, type: "character" },
    { id: 9, text: "，", pinyin: null, line: 1, type: "punctuation" },
    { id: 10, text: "一", pinyin: "yi1", line: 1, type: "character" },
    { id: 11, text: "象", pinyin: "xiang4", line: 1, type: "character" },
    { id: 12, text: "血", pinyin: "xue4", line: 1, type: "character" },
    { id: 13, text: "形", pinyin: "xing2", line: 1, type: "character" },
    { id: 14, text: "。", pinyin: null, line: 1, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "The", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "blood", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "of", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "a", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "sacrificial", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "animal,", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "offered", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "in", line: 0, type: "text" },
    { id: 15, text: " ", line: 0, type: "whitespace" },
    { id: 16, text: "sacrifice.", line: 0, type: "text" },
    { id: 17, text: " ", line: 0, type: "whitespace" },
    { id: 18, text: "Formed", line: 1, type: "text" },
    { id: 19, text: " ", line: 1, type: "whitespace" },
    { id: 20, text: "from", line: 1, type: "text" },
    { id: 21, text: " ", line: 1, type: "whitespace" },
    { id: 22, text: "a", line: 1, type: "text" },
    { id: 23, text: " ", line: 1, type: "whitespace" },
    { id: 24, text: "vessel;", line: 1, type: "text" },
    { id: 25, text: " ", line: 1, type: "whitespace" },
    { id: 26, text: "the", line: 1, type: "text" },
    { id: 27, text: " ", line: 1, type: "whitespace" },
    { id: 28, text: "stroke", line: 1, type: "text" },
    { id: 29, text: " ", line: 1, type: "whitespace" },
    { id: 30, text: "depicts", line: 1, type: "text" },
    { id: 31, text: " ", line: 1, type: "whitespace" },
    { id: 32, text: "the", line: 1, type: "text" },
    { id: 33, text: " ", line: 1, type: "whitespace" },
    { id: 34, text: "blood.", line: 1, type: "text" },
  ],
  mappings: [
    {
      id: "782aaac5-3ef3-4491-aced-df90dca3d1a2",
      sourceTokenIds: [11, 13],
      targetTokenIds: [30],
    },
    {
      id: "69b7bdcd-3d31-4536-a6b0-ba65cbae365a",
      sourceTokenIds: [0],
      targetTokenIds: [16],
    },
    {
      id: "19e74620-2a62-49e0-8bfd-b7fdc4e01616",
      sourceTokenIds: [3],
      targetTokenIds: [10, 8],
    },
    {
      id: "eaef0ead-1478-4c74-b163-8b301380ab5a",
      sourceTokenIds: [4],
      targetTokenIds: [2, 0],
    },
    {
      id: "2afa19d2-8d84-458a-ab8a-765050289352",
      sourceTokenIds: [1, 2],
      targetTokenIds: [12],
    },
    {
      id: "0246a58c-fd29-4eda-8f61-27dac2622d44",
      sourceTokenIds: [8],
      targetTokenIds: [24, 22],
    },
    {
      id: "e51b6d9e-677b-4041-82fd-9048f3496c3b",
      sourceTokenIds: [7],
      targetTokenIds: [20, 18],
    },
    {
      id: "5856ce03-b85d-4ca1-811e-33912dc20a6e",
      sourceTokenIds: [10],
      targetTokenIds: [28, 26],
    },
    {
      id: "d921b75d-7c76-4231-946b-ed5f83849668",
      sourceTokenIds: [12],
      targetTokenIds: [32, 34],
    },
  ],
} satisfies QuoteSlicerExport;
