import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const shuowenJieziOnTian = {
  meta: {
    sourceText: "天顚也。至高無上，从一大。",
    targetText:
      "天 is the highest. It is supremely high, there is nothing above it. It is composed of 一 and 大.",
    provenance: "Shuowen Jiezi",
  },
  sourceTokens: [
    { id: 0, text: "天", pinyin: "tian1", line: 0, type: "character" },
    { id: 1, text: "顚", pinyin: "dian1", line: 0, type: "character" },
    { id: 2, text: "也", pinyin: "ye3", line: 0, type: "character" },
    { id: 3, text: "。", pinyin: null, line: 0, type: "punctuation" },
    { id: 4, text: "至", pinyin: "zhi4", line: 0, type: "character" },
    { id: 5, text: "高", pinyin: "gao1", line: 0, type: "character" },
    { id: 6, text: "無", pinyin: "wu2", line: 0, type: "character" },
    { id: 7, text: "上", pinyin: "shang4", line: 0, type: "character" },
    { id: 8, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 9, text: "从", pinyin: "cong2", line: 0, type: "character" },
    { id: 10, text: "一", pinyin: "yi1", line: 0, type: "character" },
    { id: 11, text: "大", pinyin: "da4", line: 0, type: "character" },
    { id: 12, text: "。", pinyin: null, line: 0, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "天", line: 0, type: "hanzi" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "is", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "the", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "highest.", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "It", line: 1, type: "text" },
    { id: 9, text: " ", line: 1, type: "whitespace" },
    { id: 10, text: "is", line: 1, type: "text" },
    { id: 11, text: " ", line: 1, type: "whitespace" },
    { id: 12, text: "supremely", line: 1, type: "text" },
    { id: 13, text: " ", line: 1, type: "whitespace" },
    { id: 14, text: "high,", line: 1, type: "text" },
    { id: 15, text: " ", line: 1, type: "whitespace" },
    { id: 16, text: "there", line: 1, type: "text" },
    { id: 17, text: " ", line: 1, type: "whitespace" },
    { id: 18, text: "is", line: 1, type: "text" },
    { id: 19, text: " ", line: 1, type: "whitespace" },
    { id: 20, text: "nothing", line: 1, type: "text" },
    { id: 21, text: " ", line: 1, type: "whitespace" },
    { id: 22, text: "above", line: 1, type: "text" },
    { id: 23, text: " ", line: 1, type: "whitespace" },
    { id: 24, text: "it.", line: 1, type: "text" },
    { id: 25, text: " ", line: 1, type: "whitespace" },
    { id: 26, text: "It", line: 2, type: "text" },
    { id: 27, text: " ", line: 2, type: "whitespace" },
    { id: 28, text: "is", line: 2, type: "text" },
    { id: 29, text: " ", line: 2, type: "whitespace" },
    { id: 30, text: "composed", line: 2, type: "text" },
    { id: 31, text: " ", line: 2, type: "whitespace" },
    { id: 32, text: "of", line: 2, type: "text" },
    { id: 33, text: " ", line: 2, type: "whitespace" },
    { id: 34, text: "一", line: 2, type: "hanzi" },
    { id: 35, text: " ", line: 2, type: "whitespace" },
    { id: 36, text: "and", line: 2, type: "text" },
    { id: 37, text: " ", line: 2, type: "whitespace" },
    { id: 38, text: "大", line: 2, type: "hanzi" },
    { id: 39, text: ".", line: 2, type: "punctuation" },
  ],
  mappings: [
    {
      id: "8abcb668-68ce-41a9-adbc-f958e18ac0d4",
      sourceTokenIds: [0],
      targetTokenIds: [0],
    },
    {
      id: "0bcdb7d1-0850-4c1a-a263-c19631cf5b96",
      sourceTokenIds: [1],
      targetTokenIds: [6, 4],
    },
    {
      id: "e87213ad-11c1-4371-a240-4184ad318302",
      sourceTokenIds: [2],
      targetTokenIds: [2],
    },
    {
      id: "1ad2d34a-3f39-4815-8dd8-51344e59cc40",
      sourceTokenIds: [4],
      targetTokenIds: [12],
    },
    {
      id: "dcf28c9c-3e11-4a1b-b67d-893a54639d62",
      sourceTokenIds: [5],
      targetTokenIds: [14],
    },
    {
      id: "543ce091-a69c-4c1c-9688-1f6b07fcd7f1",
      sourceTokenIds: [6],
      targetTokenIds: [20],
    },
    {
      id: "e85f4136-37b9-4907-8e66-3d1aa5131472",
      sourceTokenIds: [7],
      targetTokenIds: [22],
    },
    {
      id: "29a18c3c-b312-4a12-81d4-9d662cf9ddf2",
      sourceTokenIds: [9],
      targetTokenIds: [30, 32],
    },
    {
      id: "80eb6256-c9dc-44bc-aa50-d1ac5248b886",
      sourceTokenIds: [10],
      targetTokenIds: [34],
    },
    {
      id: "476a2431-3242-409d-a3dc-2c01997752bc",
      sourceTokenIds: [11],
      targetTokenIds: [38],
    },
  ],
} satisfies QuoteSlicerExport;
