import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const shuowenJieziOnOne = {
  meta: {
    sourceText: "惟初太始，道立於一，造分天地，化成萬物。",
    targetText:
      "At the very beginning, at the great origin, the Dao was established in One. It created and separated Heaven and Earth, transforming into all things.",
    provenance: "Shuowen Jiezi",
  },
  sourceTokens: [
    { id: 0, text: "惟", pinyin: undefined, line: 0, type: "character" },
    { id: 1, text: "初", pinyin: "chu1", line: 0, type: "character" },
    { id: 2, text: "太", pinyin: "tai4", line: 0, type: "character" },
    { id: 3, text: "始", pinyin: "shi3", line: 0, type: "character" },
    { id: 4, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 5, text: "道", pinyin: "dao4", line: 0, type: "character" },
    { id: 6, text: "立", pinyin: "li4", line: 0, type: "character" },
    { id: 7, text: "於", pinyin: "wu1", line: 0, type: "character" },
    { id: 8, text: "一", pinyin: "yi1", line: 0, type: "character" },
    { id: 9, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 10, text: "造", pinyin: "zao4", line: 1, type: "character" },
    { id: 11, text: "分", pinyin: "fen1", line: 1, type: "character" },
    { id: 12, text: "天", pinyin: "tian1", line: 1, type: "character" },
    { id: 13, text: "地", pinyin: "di4", line: 1, type: "character" },
    { id: 14, text: "，", pinyin: null, line: 1, type: "punctuation" },
    { id: 15, text: "化", pinyin: "hua4", line: 1, type: "character" },
    { id: 16, text: "成", pinyin: "cheng2", line: 1, type: "character" },
    { id: 17, text: "萬", pinyin: "wan4", line: 1, type: "character" },
    { id: 18, text: "物", pinyin: "wu4", line: 1, type: "character" },
    { id: 19, text: "。", pinyin: null, line: 1, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "At", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "the", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "very", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "beginning,", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "at", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "the", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "great", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "origin,", line: 0, type: "text" },
    { id: 15, text: " ", line: 0, type: "whitespace" },
    { id: 16, text: "the", line: 1, type: "text" },
    { id: 17, text: " ", line: 1, type: "whitespace" },
    { id: 18, text: "Dao", line: 1, type: "text" },
    { id: 19, text: " ", line: 1, type: "whitespace" },
    { id: 20, text: "was", line: 1, type: "text" },
    { id: 21, text: " ", line: 1, type: "whitespace" },
    { id: 22, text: "established", line: 1, type: "text" },
    { id: 23, text: " ", line: 1, type: "whitespace" },
    { id: 24, text: "in", line: 1, type: "text" },
    { id: 25, text: " ", line: 1, type: "whitespace" },
    { id: 26, text: "One.", line: 1, type: "text" },
    { id: 27, text: " ", line: 1, type: "whitespace" },
    { id: 28, text: "It", line: 2, type: "text" },
    { id: 29, text: " ", line: 2, type: "whitespace" },
    { id: 30, text: "created", line: 2, type: "text" },
    { id: 31, text: " ", line: 2, type: "whitespace" },
    { id: 32, text: "and", line: 2, type: "text" },
    { id: 33, text: " ", line: 2, type: "whitespace" },
    { id: 34, text: "separated", line: 2, type: "text" },
    { id: 35, text: " ", line: 2, type: "whitespace" },
    { id: 36, text: "Heaven", line: 2, type: "text" },
    { id: 37, text: " ", line: 2, type: "whitespace" },
    { id: 38, text: "and", line: 2, type: "text" },
    { id: 39, text: " ", line: 2, type: "whitespace" },
    { id: 40, text: "Earth,", line: 2, type: "text" },
    { id: 41, text: " ", line: 2, type: "whitespace" },
    { id: 42, text: "transforming", line: 3, type: "text" },
    { id: 43, text: " ", line: 3, type: "whitespace" },
    { id: 44, text: "into", line: 3, type: "text" },
    { id: 45, text: " ", line: 3, type: "whitespace" },
    { id: 46, text: "all", line: 3, type: "text" },
    { id: 47, text: " ", line: 3, type: "whitespace" },
    { id: 48, text: "things.", line: 3, type: "text" },
  ],
  mappings: [
    {
      id: "fb8ab1d6-2171-47c7-99ac-d0101ef8be9e",
      sourceTokenIds: [1],
      targetTokenIds: [6, 4],
    },
    {
      id: "9d8a1d19-865e-47e5-b53d-33cfacf7d718",
      sourceTokenIds: [2],
      targetTokenIds: [12],
    },
    {
      id: "8af38239-59e3-4e7c-8d8e-65f41696f851",
      sourceTokenIds: [3],
      targetTokenIds: [14],
    },
    {
      id: "49ac3a95-1c1b-4908-a9dd-e48eb66354ee",
      sourceTokenIds: [5],
      targetTokenIds: [18],
    },
    {
      id: "7b4b759c-d11b-4b7e-a938-05592359ef48",
      sourceTokenIds: [6],
      targetTokenIds: [22, 20],
    },
    {
      id: "e147a8bf-70df-4c85-9e11-f8f6cf58ca0a",
      sourceTokenIds: [7],
      targetTokenIds: [24],
    },
    {
      id: "824611c4-d49e-40d2-a505-9001eb0bd672",
      sourceTokenIds: [8],
      targetTokenIds: [26],
    },
    {
      id: "ffcf01c3-464f-4914-96bc-0938c0c3c335",
      sourceTokenIds: [11],
      targetTokenIds: [34],
    },
    {
      id: "30c6d702-a8c9-47b3-a3a6-a5b7293003b7",
      sourceTokenIds: [12],
      targetTokenIds: [36],
    },
    {
      id: "a608f543-fc9f-4be4-a9e5-71b5ce28e6d0",
      sourceTokenIds: [13],
      targetTokenIds: [40],
    },
    {
      id: "e7819fba-f93d-4a03-b4f7-7e0c5fb1b14f",
      sourceTokenIds: [15, 16],
      targetTokenIds: [42, 44],
    },
    {
      id: "ed279995-4d7a-490c-afff-47720f28932c",
      sourceTokenIds: [17],
      targetTokenIds: [46],
    },
    {
      id: "ac17d009-49fd-41cd-bb11-483de313b6df",
      sourceTokenIds: [18],
      targetTokenIds: [48],
    },
    {
      id: "6330abf2-38c8-47f4-baca-e7374e5baee2",
      sourceTokenIds: [10],
      targetTokenIds: [30],
    },
  ],
} satisfies QuoteSlicerExport;
