import type { QuoteSlicerExport } from "../../quote-slicer-export";

export const shuowenJieziOnMo = {
  meta: {
    sourceText: "木上曰末。从木，一在其上。",
    targetText: "The top of a tree is called 末. From 木; 一 is above it.",
    provenance: "Shuowen Jiezi",
  },
  sourceTokens: [
    { id: 0, text: "木", pinyin: "mu4", line: 0, type: "character" },
    { id: 1, text: "上", pinyin: "shang4", line: 0, type: "character" },
    { id: 2, text: "曰", pinyin: "yue1", line: 0, type: "character" },
    { id: 3, text: "末", pinyin: "mo4", line: 0, type: "character" },
    { id: 4, text: "。", pinyin: null, line: 0, type: "punctuation" },
    { id: 5, text: "从", pinyin: "cong2", line: 0, type: "character" },
    { id: 6, text: "木", pinyin: "mu4", line: 0, type: "character" },
    { id: 7, text: "，", pinyin: null, line: 0, type: "punctuation" },
    { id: 8, text: "一", pinyin: "yi1", line: 0, type: "character" },
    { id: 9, text: "在", pinyin: "zai4", line: 0, type: "character" },
    { id: 10, text: "其", pinyin: "qi2", line: 0, type: "character" },
    { id: 11, text: "上", pinyin: "shang4", line: 0, type: "character" },
    { id: 12, text: "。", pinyin: null, line: 0, type: "punctuation" },
  ],
  targetTokens: [
    { id: 0, text: "The", line: 0, type: "text" },
    { id: 1, text: " ", line: 0, type: "whitespace" },
    { id: 2, text: "top", line: 0, type: "text" },
    { id: 3, text: " ", line: 0, type: "whitespace" },
    { id: 4, text: "of", line: 0, type: "text" },
    { id: 5, text: " ", line: 0, type: "whitespace" },
    { id: 6, text: "a", line: 0, type: "text" },
    { id: 7, text: " ", line: 0, type: "whitespace" },
    { id: 8, text: "tree", line: 0, type: "text" },
    { id: 9, text: " ", line: 0, type: "whitespace" },
    { id: 10, text: "is", line: 0, type: "text" },
    { id: 11, text: " ", line: 0, type: "whitespace" },
    { id: 12, text: "called", line: 0, type: "text" },
    { id: 13, text: " ", line: 0, type: "whitespace" },
    { id: 14, text: "末", line: 0, type: "hanzi" },
    { id: 15, text: ".", line: 0, type: "punctuation" },
    { id: 16, text: " ", line: 0, type: "whitespace" },
    { id: 17, text: "From", line: 0, type: "text" },
    { id: 18, text: " ", line: 0, type: "whitespace" },
    { id: 19, text: "木", line: 0, type: "hanzi" },
    { id: 20, text: ";", line: 0, type: "punctuation" },
    { id: 21, text: " ", line: 0, type: "whitespace" },
    { id: 22, text: "一", line: 0, type: "hanzi" },
    { id: 23, text: " ", line: 0, type: "whitespace" },
    { id: 24, text: "is", line: 0, type: "text" },
    { id: 25, text: " ", line: 0, type: "whitespace" },
    { id: 26, text: "above", line: 0, type: "text" },
    { id: 27, text: " ", line: 0, type: "whitespace" },
    { id: 28, text: "it.", line: 0, type: "text" },
  ],
  mappings: [
    {
      id: "69967bbd-8acd-4fad-8bdd-2e32c9937333",
      sourceTokenIds: [0],
      targetTokenIds: [8, 6],
    },
    {
      id: "738ab616-a24a-4a79-b6ad-e19f618f6843",
      sourceTokenIds: [1],
      targetTokenIds: [2, 0],
    },
    {
      id: "3923010e-ab63-4db4-8194-247eecd18b18",
      sourceTokenIds: [2],
      targetTokenIds: [12, 10],
    },
    {
      id: "313d1af2-5b26-419f-9624-3aab997ae646",
      sourceTokenIds: [3],
      targetTokenIds: [14],
    },
    {
      id: "10cdb66d-1859-4710-ae52-dedd7107154e",
      sourceTokenIds: [5],
      targetTokenIds: [17],
    },
    {
      id: "46c5a5ad-bcb2-4698-b6e2-36891f2c43cf",
      sourceTokenIds: [6],
      targetTokenIds: [19],
    },
    {
      id: "3e7ca1bd-0f58-4801-b3e4-e704a4e68cc4",
      sourceTokenIds: [8],
      targetTokenIds: [22],
    },
    {
      id: "e14e2cda-7c50-41a9-9317-e074905c32a4",
      sourceTokenIds: [9],
      targetTokenIds: [24],
    },
    {
      id: "40ca0fd2-154c-4058-b980-b2dcfcb4b949",
      sourceTokenIds: [10],
      targetTokenIds: [28],
    },
    {
      id: "81ec5d50-f844-4dc6-bad6-8a1cc7f06704",
      sourceTokenIds: [11],
      targetTokenIds: [26],
    },
  ],
} satisfies QuoteSlicerExport;
